GET http://localhost:9000/giftstore/basket?userName=pratikan

###
POST http://localhost:9000/giftstore/basket
Content-Type: application/json

{
    "userName":"pratikan",
    "modelNo":"BGO4644",
    "quantity":1
}

###
DELETE http://localhost:9000/giftstore/basket
Content-Type: application/json

{
    "userName":"pratikan",
    "modelNo":"BGO4644",
    "quantity":1
}

### 
PATCH http://localhost:9000/giftstore/basket
Content-Type: application/json

{
    "userName":"pratikan",
    "modelNo":"BGO4644",
    "quantity":4
}
