GET http://localhost:9000/giftstore/rating?userName=pujamatta&modelNo=ddsd

###
POST http://localhost:9000/giftstore/rating?userName=shreali&modelNo=SSQ1291
Content-Type: application/json

{
    "value":4.5
}

###
PATCH http://localhost:9000/giftstore/rating?userName=missula&modelNo=BGO4644
Content-Type: application/json

{
    "value":4
}
