GET http://localhost:9000/event?organizerId=2

###
POST http://localhost:9000/event
Content-Type: application/json

{
    "organizerId": 4,
    "eventName": "Sanji's wedding",
    "groomName": "Vinsmoke Sanji",
    "brideName": "Boa Hancock",
    "eventDate": "2020-10-11",
    "shift": "Night"
}

###
DELETE http://localhost:9000/event?eventId=9

###
PATCH http://localhost:9000/event
Content-Type: application/json

{
    "eventId": 5,
    "brideName": "Nico Robin",
    "eventDate": "2020-09-11",
    "shift": "Day"
}