GET http://localhost:9000/event?organizerId=1

###
GET http://localhost:9000/userhome/myevents?userName=Demented

POST http://localhost:9000/event
Content-Type: application/json

{
    "organizerId": 2,
    "eventName": "Luffy's wedding",
    "groomName": "Monkey D. Luffy",
    "brideName": "Boa Hancock",
    "eventDate": "2020-10-14",
    "shift": "Day"
}

###
DELETE http://localhost:9000/event?eventId=8

###
PATCH http://localhost:9000/event
Content-Type: application/json

{
    "eventId": 10,
    "eventStatus":"UPCOMING",
    "hostStatus":"APPROVED",
    "brideName": "Nico Robin",
    "eventDate": "2020-09-19",
    "shift": "Day"
}

