GET http://localhost:9000/guestList?eventId=6

###
POST http://localhost:9000/guestList
Content-Type: application/json

{
    "eventId":"6",
    "userName":"junushu"
}

###
DELETE http://localhost:9000/guestList
Content-Type: application/json

{
    "eventId":"6",
    "userName":"junushu"
}