GET http://localhost:9000/host?vatNo=773311
###
DELETE http://localhost:9000/host?vatNo=667724

###
PATCH http://localhost:9000/host
Content-Type: application/json

{
    "vatNo":830058,
    "profilePhoto":"C:/Users/nbhn3/Downloads/photo/p1"
}

###
GET  http://localhost:9000/host/requests?vatNo=789456

###
GET  http://localhost:9000/host/approved?vatNo=771982

###
GET  http://localhost:9000/host/upcoming?vatNo=771982

###
GET  http://localhost:9000/host/bookeddates?vatNo=789456