GET http://localhost:9000/host?vatNo=667724

###
DELETE http://localhost:9000/host?vatNo=667724

###
PATCH http://localhost:9000/host
Content-Type: application/json

{
    "vatNo":667724,
    "profilePhoto":"dummyimages2",
    "description":"dummy party palace for trial",
    "email":"dum22@gmail.com",
    "contactInfo":"041-22456",
    "latitude":"77",
    "longitude":"22",
    "totalHalls":2,
    "city":"kathmandu",
    "street":"chabahil",
    "provience":"3"
}