GET http://localhost:9000/invitation/prototype

###
GET http://localhost:9000/invitation/draft?eventId=6

###
POST http://localhost:9000/invitation/draft
Content-Type: application/json

{
    "eventId":6,
    "draft":"1234567890 jkashgfgd kadfegvh lakdnkefjbh akmlnfjskbh akmlnj",
    "backgroundimage1":"image1",
    "backgroundimage2":"image2"
}