POST http://localhost:9000/login/admin
content-type: application/json

{
    "userName": "admin",
    "password": "admin"
}

###

POST http://localhost:9000/login/user
content-type: application/json

{
       "email": "junushu@gmail.com"
}

###
POST http://localhost:9000/login/host
content-type: application/json

{
    "email": "dum2@gmail.com"
}

###

POST http://localhost:9000/signup/user
Content-Type: application/json

{
    "firstName": "Ritchie",
    "lastName": "MacVagh",
    "middleName": "",
    "userName": "rmacvagh22",
    "password": "beRfjI",
    "points": 978,
    "email": "rmacvagh01@pinterest.com",
    "mobileNo": 2147483647,
    "street": "Pepper Wood",
    "city": "Bęczarka",
    "provience": "5"
}