GET http://localhost:9000/menu?eventId=6

###
POST http://localhost:9000/menu
Content-Type: application/json

{
    "eventId": 4,
    "snacks1":"khanekura #rekya" ,
    "snacks2":"khanekura #rekya" ,
    "snacks3":"khanekura #rekya" ,
    "mainDish1":"khanekura #rekya" ,
    "mainDish2":"khanekura #rekya" ,
    "sideDish1":"khanekura #rekya" ,
    "sideDish2":"khanekura #rekya" ,
    "desert1":"khanekura #rekya" ,
    "desert2":"khanekura #rekya" ,
    "coldDrinks":"khanekura #rekya" ,
    "drinks":"khanekura #rekya" ,
    "specialDish":"khanekura #rekya" ,
    "extra":"khanekura #rekya" 
}

###
PATCH http://localhost:9000/menu?
Content-Type: application/json

{
    "menuId": 3,
    "snacks1":"khanekura #changed" ,
    "snacks2":"khanekura #changed" ,
    "snacks3":"khanekura #changed" ,
    "mainDish1":"khanekura #changed" 
}

###
DELETE http://localhost:9000/menu?menuId=1