GET http://localhost:9000/organizer?userName=Demented

###
POST http://localhost:9000/organizer
Content-Type: application/json

{
    "userName":"Demented"
}
###
DELETE http://localhost:9000/organizer
