GET http://localhost:9000/userhome

###
GET http://localhost:9000/userhome/invitationrecieved?userName=junushu

###
GET http://localhost:9000/userhome/search?value=a&&key=partypalace

###
GET http://localhost:9000/userhome/user?userName=junushu

###
POST http://localhost:9000/userhome/user
Content-Type: application/json

{
    "userName":"junushu",
    "points":30
}