GET http://localhost:9000/userhome

###
GET http://localhost:9000/userhome/invitationrecieved?userName=mda

###
GET http://localhost:9000/userhome/search?value=a&&key=partypalace

###
GET http://localhost:9000/userhome/user?userName=junushu

###
PATCH  http://localhost:9000/userhome/user
Content-Type: application/json

{
    "userName":"chankit",
    "points":30
}